# Generated by Django 3.2.8 on 2021-11-01 06:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Seven_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('seven_days_sensor', models.CharField(max_length=100)),
                ('seven_days_airkorea', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Thirty_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('thirty_days_sensor', models.CharField(max_length=100)),
                ('thirty_days_airkorea', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='sensor date published')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
        migrations.CreateModel(
            name='AirKorea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airkorea', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='airkor date published')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
    ]
