# Generated by Django 3.2.9 on 2021-11-09 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('car_number', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Thirty_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thirty_days_sensor_avg', models.FloatField(blank=True, null=True)),
                ('thirty_days_sensor_max', models.FloatField(blank=True, null=True)),
                ('thirty_days_airkorea_avg', models.FloatField(blank=True, null=True)),
                ('thirty_days_airkorea_max', models.FloatField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thirty days data published')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Seven_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seven_days_sensor_avg', models.FloatField(blank=True, null=True)),
                ('seven_days_sensor_max', models.FloatField(blank=True, null=True)),
                ('seven_days_airkorea_avg', models.FloatField(blank=True, null=True)),
                ('seven_days_airkorea_max', models.FloatField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Seven days data published')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.FloatField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sensor date published')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
        migrations.CreateModel(
            name='AirKorea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airkorea', models.FloatField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='airkor date published')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
    ]
