# Generated by Django 3.2.9 on 2021-11-11 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('car_number', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thirty_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thirty_days_sensor_avg', models.FloatField(blank=True, null=True)),
                ('thirty_days_sensor_max', models.FloatField(blank=True, null=True)),
                ('thirty_days_airkorea_avg', models.FloatField(blank=True, null=True)),
                ('thirty_days_airkorea_max', models.FloatField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thirty days data published')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Seven_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seven_days_sensor_avg', models.FloatField(blank=True, null=True)),
                ('seven_days_sensor_max', models.FloatField(blank=True, null=True)),
                ('seven_days_airkorea_avg', models.FloatField(blank=True, null=True)),
                ('seven_days_airkorea_max', models.FloatField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Seven days data published')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.FloatField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sensor date published')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
        migrations.CreateModel(
            name='AirKorea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airkorea', models.FloatField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='airkor date published')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
    ]
