# Generated by Django 3.2.9 on 2021-11-25 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('airfilter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airkorea',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 8, 13, 34, 815405, tzinfo=utc), verbose_name='airkor date published'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 8, 13, 34, 811264, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 8, 13, 34, 796989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 8, 13, 34, 812625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='qr',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 8, 13, 34, 812008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 8, 13, 34, 814721, tzinfo=utc), verbose_name='sensor date published'),
        ),
        migrations.AlterField(
            model_name='seven_days',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 8, 13, 34, 815992, tzinfo=utc), verbose_name='Seven days data published'),
        ),
        migrations.AlterField(
            model_name='thirty_days',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 8, 13, 34, 816658, tzinfo=utc), verbose_name='Thirty days data published'),
        ),
    ]
