# Generated by Django 3.2.8 on 2021-11-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airfilter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airkorea',
            old_name='machine_id',
            new_name='machine',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='machine_id',
            new_name='machine',
        ),
        migrations.RenameField(
            model_name='seven_days',
            old_name='machine_id',
            new_name='machine',
        ),
        migrations.RenameField(
            model_name='thirty_days',
            old_name='machine_id',
            new_name='machine',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='machine_id',
        ),
    ]
