# Generated by Django 3.2.9 on 2021-11-19 17:03

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airfilter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='gps',
        ),
        migrations.AlterField(
            model_name='airkorea',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 3, 49, 86774), verbose_name='airkor date published'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='car_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 3, 49, 82530)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 3, 49, 86238), verbose_name='sensor date published'),
        ),
        migrations.AlterField(
            model_name='seven_days',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 3, 49, 87265), verbose_name='Seven days data published'),
        ),
        migrations.AlterField(
            model_name='thirty_days',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 3, 49, 87827), verbose_name='Thirty days data published'),
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.URLField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 3, 49, 83628))),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 3, 49, 83104))),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine')),
            ],
        ),
    ]
