# Generated by Django 3.2.9 on 2021-11-19 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airfilter', '0002_auto_20211119_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airkorea',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 9, 13, 804873), verbose_name='airkor date published'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 9, 13, 801158)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 9, 13, 800569)),
        ),
        migrations.AlterField(
            model_name='qr',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 9, 13, 801679)),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 9, 13, 804347), verbose_name='sensor date published'),
        ),
        migrations.AlterField(
            model_name='seven_days',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 9, 13, 805370), verbose_name='Seven days data published'),
        ),
        migrations.AlterField(
            model_name='thirty_days',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 17, 9, 13, 805933), verbose_name='Thirty days data published'),
        ),
    ]
