# Generated by Django 3.2.9 on 2021-11-25 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airfilter', '0002_auto_20211125_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airkorea',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='airkor date published'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='qr',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='sensor date published'),
        ),
        migrations.AlterField(
            model_name='seven_days',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Seven days data published'),
        ),
        migrations.AlterField(
            model_name='thirty_days',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Thirty days data published'),
        ),
    ]
