# Generated by Django 3.2.9 on 2021-11-08 03:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airfilter', '0003_alter_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seven_days',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine'),
        ),
        migrations.AlterField(
            model_name='seven_days',
            name='seven_days_airkorea',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=8),
        ),
        migrations.AlterField(
            model_name='seven_days',
            name='seven_days_sensor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=8),
        ),
        migrations.AlterField(
            model_name='thirty_days',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airfilter.machine'),
        ),
        migrations.AlterField(
            model_name='thirty_days',
            name='thirty_days_airkorea',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=31),
        ),
        migrations.AlterField(
            model_name='thirty_days',
            name='thirty_days_sensor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=31),
        ),
    ]
