# Generated by Django 3.2.9 on 2021-11-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airfilter', '0004_auto_20211108_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airkorea',
            name='airkorea',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor',
            field=models.FloatField(),
        ),
    ]
