# Generated by Django 3.2.9 on 2021-11-08 06:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airfilter', '0005_auto_20211108_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='seven_days',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Seven days data published'),
        ),
        migrations.AddField(
            model_name='thirty_days',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thirty days data published'),
        ),
        migrations.AlterField(
            model_name='airkorea',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='airkor date published'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='sensor date published'),
        ),
        migrations.AlterField(
            model_name='seven_days',
            name='seven_days_airkorea',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2),
        ),
        migrations.AlterField(
            model_name='seven_days',
            name='seven_days_sensor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2),
        ),
        migrations.AlterField(
            model_name='thirty_days',
            name='thirty_days_airkorea',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=31), size=2),
        ),
        migrations.AlterField(
            model_name='thirty_days',
            name='thirty_days_sensor',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=31), size=2),
        ),
    ]
