version: 0.0

os: linux
files:

  - source: django
    destination: /home/ubuntu/django
  - source: mosquitto
    destination: /etc/mosquitto
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/KRservertime
      runas: root


