version: 0.0

os: linux
files:

  - source: django
    destination: /home/ubuntu/django
  - source: mosquitto
    destination: /etc/mosquitto
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/KRservertime.sh
      runas: root
  AfterInstall:
    - location: scripts/pip_check.sh
      timeout: 300
      runas: root      
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root




