version: 0.0

os: linux
files:

  - source: django
    destination: /home/ubuntu/django

file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/KRservertime.sh
      runas: root
  AfterInstall:
    - location: scripts/pip_check.sh
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root



